[[Xorg_libSM]]
arch = "aarch64"
git-tree-sha1 = "254286598d98b9a2f2ddf8573e032ad2a25aa370"
libc = "glibc"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "4da5da195966b81b2a447a20507abbe254035cd4cafc816f62122598ed0b055e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.aarch64-linux-gnu.tar.gz"
[[Xorg_libSM]]
arch = "aarch64"
git-tree-sha1 = "68d83f8a64b09899d613d875d916e526e368ae06"
libc = "musl"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "d2b4f01cae2398d644cfde33cfc4000181a76b2bc2c03223ce09080ea1c6612f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.aarch64-linux-musl.tar.gz"
[[Xorg_libSM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "a247f15daaaca32e8e449f4d922c1765204b291f"
libc = "glibc"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "a7812dc9a2214adfe0117401db29686f66afd5202416c0eb23a1e7d6a512a782"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.armv6l-linux-gnueabihf.tar.gz"
[[Xorg_libSM]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "7ddd7afbdedf05f72561049356c6171dec2dcf4c"
libc = "musl"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "b4fd9bf07bb1dffda83caca2e18c7555fbe3f098a47b8527adca2656a2e67d9e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.armv6l-linux-musleabihf.tar.gz"
[[Xorg_libSM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a0cb5d8549e8cacfbcadda1aa2812e0327191092"
libc = "glibc"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "91d42bf1a199dc2e342f9ca7db2f63255496e691c0d6efda794632bf24f8f6ca"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.armv7l-linux-gnueabihf.tar.gz"
[[Xorg_libSM]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "61433dc40ecc78571ca34cfb6de06d33a1a86fa4"
libc = "musl"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "361ebed24725ed8e78c2b9d4e36647280ea1b0e6f48fb3fad4957bdb9585465e"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.armv7l-linux-musleabihf.tar.gz"
[[Xorg_libSM]]
arch = "i686"
git-tree-sha1 = "432011622b2d35b5fec7c199dfd77ac74206f3f2"
libc = "glibc"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "abccfb751e919bc6555898f865e2d88f297363b24ab7e6162592e603415edfd0"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.i686-linux-gnu.tar.gz"
[[Xorg_libSM]]
arch = "i686"
git-tree-sha1 = "0c683ad685ef1497244776f578d33ad09be06146"
libc = "musl"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "82bd1c3dde35bf6b7511121413c412c4dc486ced1afe982508ec29cc637fb5ca"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.i686-linux-musl.tar.gz"
[[Xorg_libSM]]
arch = "powerpc64le"
git-tree-sha1 = "bc8c92c3203e9a8959694d83b52052a823a1280f"
libc = "glibc"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "f5d8723c26ca5553daee827467bf701c64f110e26248f52ba5fe4c872b45392f"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.powerpc64le-linux-gnu.tar.gz"
[[Xorg_libSM]]
arch = "x86_64"
git-tree-sha1 = "b0d2538004dda9eb6449b72b0b85703aeac30a66"
libc = "glibc"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "e875b5e9d8c83f58fede7c0e6e6b7c0aa91106e046063d3fc3e0b6d43b85e02c"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.x86_64-linux-gnu.tar.gz"
[[Xorg_libSM]]
arch = "x86_64"
git-tree-sha1 = "4f07a80e26ab21a1685292283aa89a827203870a"
libc = "musl"
os = "linux"

    [[Xorg_libSM.download]]
    sha256 = "1c49d4bc4ad826ad191a97d3c8a1b715c3dee828ed27f7c4ec13342c1a458e78"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.x86_64-linux-musl.tar.gz"
[[Xorg_libSM]]
arch = "x86_64"
git-tree-sha1 = "d2ae7437ed8e296cd3435f52afdf96750ec53547"
os = "freebsd"

    [[Xorg_libSM.download]]
    sha256 = "29e0eda6428a4844decc52da3d615ec310f7e14713883436130597a5c1bb0138"
    url = "https://github.com/JuliaBinaryWrappers/Xorg_libSM_jll.jl/releases/download/Xorg_libSM-v1.2.4+0/Xorg_libSM.v1.2.4.x86_64-unknown-freebsd.tar.gz"
